Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-09, with the labels that each got.

#149 Fix initials images groups watch
  vue/components/forms/personalization-form/initials-images.vue
Labels: bug

#148 Initials images loaded class
  vue/components/forms/personalization-form/initials-images.vue
Labels: enhancement

#146 #562: Personalization support missing properties
  vue/components/forms/personalization-form/reference.vue
Labels: bug

#151 Add null loaders for tests
  package.json
  vue/test/webpack.config.js
Labels: back-port 🔮

#152 Typo fix
  vue/components/organisms/personalization/personalization.vue
Labels: bug

#150 Thumbnails groups component
  .storybook/config.js
  vue/components/molecules/index.js
  vue/components/molecules/thumbnails-groups/index.js
  vue/components/molecules/thumbnails-groups/thumbnails-groups.stories.js
  vue/components/molecules/thumbnails-groups/thumbnails-groups.vue
Labels: enhancement

#153 #351 Custom ripe instance and ignore bus support
  vue/components/organisms/configurator/configurator.vue
Labels: enhancement

#155 New polyfill model
  package.json
  vue/test/setup.js
  vue/test/webpack.config.js
Labels: enhancement
