Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-06, with the labels that each got.

#120 First unit test
  js/ui/base-size/base-size.vue
  package.json
  vue/test/base.js
  vue/test/components/button/button.test.js
  vue/test/mocks/index.js
  vue/test/mocks/mixins/device.js
  vue/test/mocks/mixins/index.js
  vue/test/setup.js
  vue/test/webpack.config.js
Labels: enhancement

#119 #467 Fixed restrictions alert not closing when undo button is clicked
  vue/components/molecules/restrictions-alert/restrictions-alert.vue
Labels: bug

#123 Fix test $bus and add to Github workflow
  .github/workflows/main.yml
  vue/test/base.js
Labels: bug

#127 Fix unit test description
  vue/test/components/button/button.test.js
Labels: enhancement

#124 #122 Unit test for the restrictions-alert fix
  vue/test/base.js
  vue/test/components/restrictions-alert/restrictions-alert.test.js
  vue/test/mocks/filters/index.js
  vue/test/mocks/filters/locale.js
  vue/test/mocks/index.js
  vue/test/mocks/mixins/index.js
Labels: unit-testing

#128 #427 Fix locales reactivity
  js/base/main.js
  js/locale/locale.js
  vue/components/organisms/pickers/pickers.vue
Labels: bug, enhancement

#129 #116: Check if personalization's dynamic component is null
  vue/components/organisms/personalization/personalization.vue
Labels: enhancement

#131 Add disabled prop to button
  vue/components/atoms/button/button.stories.js
  vue/components/atoms/button/button.vue
Labels: enhancement, fast-track
