Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-11, with the labels that each got.

#169 #644 Add price_error bind
  js/base/main.js
Labels: bug, enhancement

#162 #608 Add localized computed method to subscribe to locale store changes
  vue/components/forms/personalization-form/reference.vue
  vue/components/forms/size-form/reference.vue
  vue/components/molecules/restrictions-alert/restrictions-alert.vue
  vue/components/molecules/tabs/tab.vue
  vue/components/organisms/configurator/configurator.vue
  vue/components/organisms/personalization/personalization.vue
  vue/components/organisms/size/size.vue
  vue/mixins/utils.js
  vue/plugins/locale.js
  vue/test/mocks/mixins/index.js
  vue/test/mocks/mixins/locale.js
Labels: enhancement, talk

#173 #664 Add missing personalization locale keys
  bundles/config.en_us.json
  bundles/config.ja_jp.json
  bundles/config.zh_cn.json
  vue/components/forms/personalization-form/reference.vue
Labels: bug, enhancement

#172 #644 Add missing tab properties
  bundles/config.en_us.json
  bundles/config.ja_jp.json
  bundles/config.zh_cn.json
  vue/components/forms/personalization-form/reference.vue
Labels: bug, enhancement

#176 Object.assign before saving to store
  vue/store.js
Labels: bug

#177 Fix locales for font size
  bundles/config.en_us.json
  bundles/config.ja_jp.json
  bundles/config.zh_cn.json
Labels: bug

#170 #70 Personalization validation for apply button
  vue/components/forms/personalization-form/reference.vue
  vue/components/organisms/personalization/personalization.vue
  vue/mixins/logic.js
Labels: architecture 🏚, enhancement, risky ❕, talk, unit-testing

#179 #688: Improve disable apply default condition
  vue/components/forms/personalization-form/reference.vue
Labels: bug, regression

#166 #351 Prop onError
  vue/components/organisms/configurator/configurator.vue
Labels: enhancement, fast-track

#181 #685 Add SDK locales to localePlugin's localeMap
  js/base/main.js
  js/locale/model-locale-loader.js
  package.json
  vue/components/forms/size-form/reference.vue
Labels: bug, enhancement

#165 #351 Frame change via prop
  vue/components/organisms/configurator/configurator.vue
Labels: enhancement

#186 Fix SDK init: use options
  js/base/main.js
Labels: bug, regression

#190 Hide group label when there is a single group
  vue/components/forms/personalization-form/reference.vue
Labels: enhancement

#189 Refactor validation to allPropertiesOrEmpty
  vue/components/forms/personalization-form/reference.vue
  vue/mixins/logic.js
Labels: enhancement
