Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-12, with the labels that each got.

#184 refreshInitialsData only when needed
  js/base/main.js
  vue/store.js
Labels: enhancement

#191 #698 Add validation reset on pre_config
  vue/components/organisms/personalization/personalization.vue
Labels: bug, unit-testing

#192 Pick size when there is a single option
  vue/components/forms/size-form/reference.vue
  vue/components/organisms/size/size.vue
Labels: enhancement

#193 Store size active
  vue/components/organisms/size/size.vue
  vue/store.js
Labels: bug, p-medium

#182 #691: Fix size text locale
  vue/components/organisms/size/size.vue
Labels: bug

#175 #671 Initials input validation
  vue/components/organisms/personalization/personalization.vue
  vue/mixins/logic.js
  vue/store.js
  vue/test/base.js
  vue/test/mixins/logic.test.js
Labels: bug, enhancement

#194 hideInactive on initials-images
  vue/components/forms/personalization-form/initials-images.vue
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement

#185 #673: Centering scroll logic applied to parts+materials
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement

#195 #689 Fix square swatches for webkit
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#198 Fix engraving without initials
  vue/components/organisms/personalization/personalization.vue
  vue/mixins/logic.js
Labels: bug

#204 Fix DKU init initials extra
  js/base/main.js
  vue/mixins/logic.js
Labels: bug

#203 Fix DKU init loop
  js/base/main.js
  vue/mixins/logic.js
Labels: bug

#202 Fine-grained error handling of 'runLogic'
  vue/store.js
Labels: enhancement
