Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-10, with the labels that each got.

#156 Add initials capabilities to store and logicMixin
  js/base/main.js
  vue/components/molecules/thumbnails-groups/thumbnails-groups.vue
  vue/mixins/logic.js
  vue/store.js
Labels: enhancement

#158 #600: Fix storybook deprecated configs
  .storybook/addons.js
  .storybook/main.js
  .storybook/preview.js
  package.json
Labels: back-port 🔮, enhancement

#160 Fixed pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#159 #609 Fixed sizes genders not being translated
  vue/components/forms/size-form/reference.vue
Labels: bug

#163 Remove .text() from runLogicP call
  js/base/main.js
Labels: enhancement

#164 Bump ripe-sdk version
  package.json
Labels: enhancement

#167 Fix test watch script
  package.json
Labels: bug

#168 #172 Add extra icons
  vue/assets/icons/extra/font_trimming.svg
  vue/assets/icons/extra/hat.svg
  vue/assets/icons/extra/letter_spacing.svg
  vue/assets/icons/extra/line_height.svg
  vue/assets/icons/extra/mirror_horizontal.svg
  vue/assets/icons/extra/mirror_vertical.svg
  vue/assets/icons/extra/options.svg
  vue/components/atoms/icon/icon.vue
Labels: back-port 🔮, enhancement
