Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-07, with the labels that each got.

#132 #503 Add semantic classes to generic personalization
  vue/components/forms/personalization-form/reference.vue
Labels: enhancement

#134 Fix generic plugin select class name
  vue/components/forms/personalization-form/reference.vue
Labels: back-port 🔮, bug, regression

#143 #540 Filter genders sizes
  vue/components/forms/size-form/reference-multi.vue
  vue/components/forms/size-form/reference.vue
Labels: enhancement, reward 🏆️, side-quest ✨

#141 #534 Fixed initials locales not updating
  vue/components/forms/personalization-form/reference.vue
Labels: bug
