Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-05, with the labels that each got.

#102 Clear dku and product_id on URL change
  js/util/url-changer.js
Labels: enhancement

#103 #234: Fix regression by re-adding slot
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#104 #341 Await unbinds
  vue/components/atoms/thumbnail/thumbnail.vue
  vue/components/forms/personalization-form/initials-images.vue
  vue/components/organisms/configurator/configurator.vue
Labels: bug

#108 Fix modal padding in firefox
  vue/components/molecules/modal/modal.vue
Labels: bug, risky

#106 #348 RIPE White Tech Mode plugin: see/change RIPE SDK options
  js/base/main.js
  vue/store.js
Labels: enhancement

#111 #441: Copy all RIPE SDK config options
  .github/workflows/main.yml
  .travis.yml
  js/base/main.js
  package.json
  vue/store.js
Labels: enhancement

#112 #448: Fix entering with product ID or DKU
  js/base/main.js
Labels: bug

#113 Image component with fallback src.
  vue/components/atoms/image/image.vue
Labels: enhancement, p-medium

#115 Fix default prop
  vue/components/molecules/tabs/tab.vue
Labels: bug
