Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2020-08, with the labels that each got.

#144 Normalize scripts
  .github/workflows/main.yml
  .travis.yml
  package.json
Labels: enhancement

#145 Fix engraving for generic personalization
  vue/components/forms/personalization-form/reference.vue
Labels: bug

#147 #561 Sync theme with URL
  js/base/main.js
  js/util/url-changer.js
  vue/store.js
Labels: enhancement, side-quest ✨
