Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2021-07, with the labels that each got.

#253 feat: add open icon to initials
  CHANGELOG.md
  vue/components/forms/personalization-form/initials-images.vue
Labels: dior, enhancement

#251 #871 Improve personalization mode
  vue/components/forms/personalization-form/initials-images.vue
Labels: enhancement

#254 fix: set correct configurator size on init
  CHANGELOG.md
  vue/components/organisms/configurator/configurator.vue
Labels: bug

#255 version: 0.12.3
  CHANGELOG.md
  package.json
Labels: enhancement
