Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2021-01, with the labels that each got.

#205 Fixed storybook not being in fullscreen
  .storybook/preview.js
Labels: bug

#206 Rename Zeit do Vercel
  README.md
Labels: documentation, enhancement

#207 chore: rename now to vercel
  package.json
  vercel.json
Labels: enhancement

#208 fix: tolerate pickers disappearing
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#209 fix: react to locale map changes
  vue/plugins/locale.js
Labels: bug

#197 #673: Scroll right and left centered
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement

#183 #673: Polish scroll arrows (color scroll arrow)
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement, fast-track

#211 fix: fix locale reactivity by using a defensive copy
  vue/plugins/locale.js
Labels: bug

#212 fix: fix regression in locale fallback
  vue/plugins/locale.js
Labels: bug, regression

#210 feat: add initials-images initialsBuilder watcher
  vue/components/forms/personalization-form/initials-images.vue
Labels: enhancement

#213 #673: Fix colors scroll behaviour and materials arrows in desktop
  vue/components/organisms/pickers/pickers.vue
Labels: bug
