Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2021-05, with the labels that each got.

#240 version: 0.10.6
  CHANGELOG.md
  package.json
Labels: enhancement

#241 fix: avoid calling 3DB logic methods with undefined ctx
  CHANGELOG.md
  vue/components/forms/personalization-form/reference.vue
  vue/store.js
Labels: bug

#243 feat: set default size on model config
  CHANGELOG.md
  js/base/main.js
  vue/components/organisms/personalization/personalization.vue
  vue/components/organisms/size/size.vue
  vue/store.js
Labels: enhancement

#244 fix: size selection regression
  CHANGELOG.md
  vue/store.js
Labels: bug, regression

#245 version: 0.11.1
  CHANGELOG.md
  package.json
Labels: enhancement

#246 fix: storybook keeps reloading
  .storybook/main.js
  package.json
Labels: back-port 🔮, bug

#247 fix: missing size text on summary
  CHANGELOG.md
  vue/store.js
Labels: bug, regression
