Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2021-02, with the labels that each got.

#214 #697: fix locale permutation
  js/locale/model-locale-resolver.js
  test/locale/model-locale-resolver.js
Labels: bug

#215 #673: Polish picker scroll arrows
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#217 feat: propagate auth event
  js/base/main.js
Labels: enhancement

#216 feat: use SDK toLocaleModel
  js/locale/model-locale-resolver.js
  package.json
  test/locale/model-locale-resolver.js
  test/setup.js
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement, risky ❕

#218 Fix storybook component search
  vue/components/atoms/button-platforme/button-platforme.stories.js
  vue/components/atoms/button/button.stories.js
  vue/components/atoms/icon/icon.stories.js
  vue/components/atoms/image/image.stories.js
  vue/components/atoms/loader/loader.stories.js
  vue/components/molecules/keyboard/keyboard.stories.js
  vue/components/molecules/thumbnails-groups/thumbnails-groups.stories.js
Labels: back-port 🔮, bug, enhancement

#219 #673: Fix center same material
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#171 #641 Add fix for initials_extra event not updating initials and engraving
  js/util/index.js
  js/util/ripe.js
  vue/components/organisms/personalization/personalization.vue
  vue/mixins/logic.js
  vue/store.js
Labels: bug, fast-track, risky ❕

#178 Fix personalization modal properties locale reactivity
  js/locale/locale.js
  js/locale/model-locale-loader.js
Labels: bug

#221 #768 Fix configurator options reactivity
  vue/components/organisms/configurator/configurator.vue
Labels: bug, enhancement

#220 #673: scrollColors when colorToggle is false
  vue/components/organisms/pickers/pickers.vue
Labels: bug

#223 #761 Using hasInitialsRadius to control personalization image border radius
  js/base/main.js
  vue/components/forms/personalization-form/reference.vue
  vue/store.js
Labels: enhancement

#225 #761 Fix duplicate borderRadius
  vue/components/forms/personalization-form/reference.vue
Labels: bug

#228 #641 Bump package - ripe-sdk version
  package.json
Labels: enhancement

#226 #768 Fix setRipeOptions
  js/base/main.js
Labels: bug

#224 #768 Add size to ripeState
  js/base/main.js
Labels: enhancement

#229 #768 Add yonius casting to _field method
  js/base/main.js
  package.json
Labels: enhancement

#230 fix: remove product ID from options
  js/base/main.js
Labels: bug, risky ❕, talk

#227 #44 Using newly implemented ripe-sdk locale methods
  js/locale/model-locale-resolver.js
  package.json
Labels: enhancement
