Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2021-04, with the labels that each got.

#234 fix: build by adding vue-loader
  package.json
Labels: back-port 🔮, bug

#235 feat: Add height as prop
  vue/components/forms/personalization-form/initials-images.vue
Labels: enhancement

#236 fix: initials images size regression
  vue/components/forms/personalization-form/initials-images.vue
Labels: bug, regression

#237 #845 Add missing variant to _buildConfig
  js/base/main.js
Labels: bug

#238 version: 0.10.5
  CHANGELOG.md
  package.json
Labels: enhancement

#239 Bump versions: ripe-sdk
  package.json
Labels: enhancement
