Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2022-03, with the labels that each got.

#289 #971 Features: reacting to open-externally for base plugins
  CHANGELOG.md
  vue/components/forms/personalization-form/reference.vue
Labels: enhancement

#290 feat: bump dependencies
  CHANGELOG.md
  package.json
Labels: enhancement

#291 #978: Initials images minimum height and undefined width/height support
  CHANGELOG.md
  vue/components/forms/personalization-form/initials-images.vue
Labels: enhancement

#293 version: 0.23.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#295 feat: bump ripe-sdk version to 0.24.0
  package.json
Labels: enhancement

#297 fix: remove default value of `minWidth` in initials-images
  CHANGELOG.md
  vue/components/forms/personalization-form/initials-images.vue
Labels: bug

#298 #996: Support for showing videos in White - thumbnails and configurator changes
  CHANGELOG.md
  vue/components/atoms/thumbnail/thumbnail.vue
  vue/components/molecules/thumbnails/thumbnails.vue
  vue/components/organisms/configurator/configurator.vue
Labels: enhancement
