Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2022-05, with the labels that each got.

#302 #1026 Add versions to all plugins
  CHANGELOG.md
  js/locale/dom-locale-loader.js
  js/locale/file-locale-loader.js
  js/locale/locale.js
  js/locale/model-locale-loader.js
  js/locale/model-locale-resolver.js
  js/ui/base-personalization/base-personalization.js
  js/ui/base-size/base-size.js
  js/util/device.js
  js/util/url-changer.js
Labels: enhancement

#303 feat: add html support to ´alert´ component
  CHANGELOG.md
  vue/components/atoms/alert/alert.vue
Labels: enhancement, p-medium

#266 Reload locale bundle for size and scale when locale changes
  CHANGELOG.md
  js/base/main.js
  js/locale/model-locale-loader.js
  package.json
  vue/components/organisms/pickers/pickers.vue
Labels: bug, risky ❕, blocked ⛔, stale

#299 #978: Support for personalization in the same environment as the configurator
  CHANGELOG.md
  package.json
  vue/components/atoms/thumbnail/thumbnail.vue
  vue/components/forms/personalization-form/initials-images.vue
  vue/components/molecules/thumbnails/thumbnails.vue
  vue/components/organisms/configurator/configurator.vue
  vue/mixins/frame.js
  vue/mixins/index.js
Labels: enhancement, talk 🎤, review-merge 💪

#306 fix: eslint errors
  CHANGELOG.md
  package.json
Labels: bug, back-port 🔮
