Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2022-02, with the labels that each got.

#282 feat: support for new webpack and bump dependencies
  .storybook/main.js
  .storybook/webpack.config.js
  CHANGELOG.md
  index.js
  package.json
  svgo.config.js
  test/locale/model-locale-resolver.js
  test/setup.js
  vue/components/atoms/button/button.vue
  vue/components/atoms/icon/icon.vue
  vue/components/organisms/pickers/pickers.vue
  vue/components/organisms/size/size.vue
  vue/mixins/device.js
  vue/test/setup.js
  vue/test/webpack.config.js
  webpack.config.js
Labels: enhancement

#284 #962: Fix drag indicator in configurator
  CHANGELOG.md
  vue/components/organisms/configurator/configurator.vue
Labels: bug

#285 revert: node-fetch bump
  CHANGELOG.md
  package.json
  vue/test/setup.js
Labels: bug

#283 #963: open externally read from context features
  CHANGELOG.md
  vue/components/organisms/personalization/personalization.vue
Labels: enhancement

#286 fix: revert to node-fetch 2 and added workaround
  test/locale/model-locale-resolver.js
  test/setup.js
Labels: bug

#288 feat: added getter `getSizeState` to the store
  CHANGELOG.md
  package.json
  vue/store.js
Labels: bug, back-port 🔮
