Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2022-06, with the labels that each got.

#308 fix: set store locale
  js/locale/locale.js
  package.json
Labels: bug, no-changelog

#309 feat: bump packages
  CHANGELOG.md
  package.json
Labels: enhancement

#310 version: 0.29.0
  CHANGELOG.md
  package.json
Labels: release 🎉
