Repository ripe-tech/ripe-commons-pluginus, pull requests merged in 2022-11, with the labels that each got.

#312 #1078 Display restricted options
  CHANGELOG.md
  vue/components/organisms/pickers/pickers.vue
Labels: enhancement

#313 #1013 Enhace `show_frame` with options and modify `thumbnail` component `onClick` action
  CHANGELOG.md
  vue/components/atoms/thumbnail/thumbnail.vue
  vue/components/organisms/configurator/configurator.vue
Labels: enhancement

#314 chore: version 0.30.0 :rainbow:
  CHANGELOG.md
  package.json
Labels: release 🎉

#315 chore: 0.30.1
  CHANGELOG.md
  package.json
Labels: release 🎉

#316 #1089 Fix storybook build and vercel deployment
  CHANGELOG.md
  package.json
Labels: bug

#317 chore: revert temp fix
  package.json
Labels: no-changelog
